### ISSUE TITLE
Use microk8s enable helm in offline environment

### ISSUE THREAD

**Issue by deruci** [canonical/microk8s#1184]
This issue is request for supporting some offline mode(w/o connectivity) for "enable" command.
For microk8s, I can download required files and could install by following below:
![image](https://user-images.githubusercontent.com/5226447/81375440-7bd76380-913c-11ea-9950-5eb41fa45791.png)

But It seems that "enable" command doesn't support any offline environment currently.
Is there any other way to use ADDON features from "enable" command in offline environment?
Specifically, I currently need to use helm and gpu ADDON feature.

**Comment by balchua** [comment]
MicroK8s isn't packaging the addon together with the snap.  
Im guessing the easiest way is to setup a proxy while setting up your environment.

To use a proxy with MicroK8s, you can follow this doc.
https://microk8s.io/docs/install-proxy

**Comment by goal86sg** [comment]
addons like kubeflow, metallb,promethus, linkerd, istio are they able to be enabled on a offline environment once microk8s offline snap is installed? What can be offline enabled by default and what cant be? Are there any way we can deploy this in an airgap offline environment?

**Comment by balchua** [comment]
There is a work to allow side loading images for situations where you dont have access to internet.

https://github.com/ubuntu/microk8s/pull/1295

**Comment by Purneau** [comment]
Any updates on this?

**Comment by balchua** [comment]
@Purneau currently microk8s doesn't package the images.  One has to manually download the images or setup proxies as explained here https://microk8s.io/docs/install-proxy.
Although there is a plan to allow sideloading images.  No definite timeline there.

**Comment by Purneau** [comment]
What is maybe good to mention to others new to this subject (because from the docs to me it was not clear straight away): 

Contrary to what the docs (https://microk8s.io/docs/install-alternatives#heading--offline) suggest: there are multiple addons, like `dns`, `storage`, `rbac`, that don't require a proxy to be deployed in an offline environment. If you follow these instructions (https://microk8s.io/docs/registry-images) to import the required docker images, your addons will be activated just fine. 

Next to this, the docs mention that the core snap should be installed on non-Ubuntu systems only. However, Ubuntu systems (at least Ubuntu Server 20.04.1) also require the `core` snap as they only have the `core18` snap installed.

The correct commands in that case become:
```
    sudo snap ack ./mk8s/core_10185.assert
    sudo snap install ./mk8s/core_10185.snap
    sudo snap ack ./mk8s/microk8s_1769.assert
    sudo snap install ./mk8s/microk8s_1769.snap --classic
```

**Comment by rere8020** [comment]
If I were to build a server online, install the snaps needed for microk8s then enable all the add-ons so that it can go and pull everything. At this point I could take a image of this machine and spin another machine up (offline) with all the dependencies already on there, potentially? Has anyone tried that?

**Comment by Purneau** [comment]
> If I were to build a server online, install the snaps needed for microk8s then enable all the add-ons so that it can go and pull everything. At this point I could take a image of this machine and spin another machine up (offline) with all the dependencies already on there, potentially? Has anyone tried that?

What do you mean with an image? If you mean like a VM snapshot, I see no reason why it shouldn’t work. 
We performed multiple fully offline deployments using the above strategy (installing the snaps and importing the necessary docker images)

**Comment by rere8020** [comment]
Yes, taking a snapshot. I will try this to see how it goes. Thanks!

**Comment by omrozowicz-splunk** [comment]
Not sure if it would be useful to anyone at this point, but I imported the helm addon in an offline environment by modifying microk8s enable script. In order to do this you need to know your system's architecture:

**Comment by balchua** [comment]
Thanks @omrozowicz-splunk for this tip.  But from MicroK8s v1.25 helm3 is included in the snap and there is no need to explicitly enable it.

**Comment by yanisks** [comment]
NAME              STATUS     ROLES    AGE    VERSION
preprod-sv78awx   NotReady   <none>   145m   v1.27.2

**Comment by ktsakalozos** [comment]
Hi @yanisks, are you following one of the scenarios in https://microk8s.io/docs/install-offline ?
