### ISSUE TITLE
Python addons should be able to use the python extension

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical/microk8s#1241]
This line prevents the use of python extension on files for addons. For example, enable.kubeflow.sh is a python addon, but uses the bash extension because of how the wrapper is configured. An option would be to look for addons with either .sh or .py extensions.  https://github.com/ubuntu/microk8s/blob/c256d7a007e2d5a6620196e778839d4dc9499064/microk8s-resources/wrappers/microk8s-enable.wrapper#L38

**Comment by ktsakalozos** [comment]
Thank you for spotting this and suggesting a fix @camille-rodriguez. We could even have a .* to support any extension.

Would you (or anyone else) be interested in a PR?

**Comment by camille-rodriguez** [comment]
@ktsakalozos Happy to help, I will look into it. I'm no expert in bash scripting, but I doubt something as simple as * exists in bash. We'll probably have to loop over the actions to find the correct one, since the following line needs the full path to launch the wrapper.

**Comment by joedborg** [comment]
If it's just py and sh, we could do `.{py,sh}`.  Depends what we want to allow I guess.

**Comment by joedborg** [comment]
Or do a similar to what I had to do with dashboard-proxy, where we have a shell wrapper around Python (useful for injecting the right environment) https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-dashboard-proxy.wrapper

**Comment by camille-rodriguez** [comment]
I submitted a PR, let me know what you think @joedborg @ktsakalozos ! :)

**Comment by anushkrishnav** [comment]
I am intrested

**Comment by krisstern** [comment]
Is anyone working on this issue at the moment?

**Comment by krisstern** [comment]
Hi @camille-rodriguez Is it okay for me to take the modifications you have tried to make in #1248 and submit another patch to follow up on this issue? I could submit a PR soon.

**Comment by ktsakalozos** [comment]
@krisstern you can take over this PR. Thank you.

**Comment by krisstern** [comment]
Thanks @ktsakalozos! I will work on a PR for the issue then.

**Comment by krisstern** [comment]
So was able to test install `microk8s` without the suggested changes first using LXD according to https://github.com/ubuntu/microk8s/blob/master/docs/build.md#building-the-snap-using-lxd on my ubuntu for arm64, but seems `multipass` is not happy with this architecture. So will need to take extra time to retry everything using my ubuntu for intel setup, otherwise seems like not an ideal situation.

**Comment by krisstern** [comment]
After some careful study of the current code base I think we can close this issue, as the original code has been rewritten in a way that this issue is no longer relevant. But some changes might still be needed for the changing of the name of https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.kubeflow.sh to a `.py` extension though. I will open a new issue and follow up with a PR for this. 

See:
1. https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-disable.wrapper
2. https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-enable.wrapper

**Comment by krisstern** [comment]
I have just submitted PR #2795 to fix the addon extensions problem.
