### ISSUE TITLE
Admin password no longer honored after upgrading to 1.19

### ISSUE THREAD

**Issue by jazarja** [canonical/microk8s#1552]
I have microk8s 1.18 installation, recently it was upgraded to 1.19

After upgrade, I found my kubectl does not work

> $ microk8s kubectl top node
error: You must be logged in to the server (Unauthorized)

My **~/.kube/config** is exactly the same as **/var/snap/microk8s/current/credentials/client.config**

### The issue

**In microk8s 1.19, kubectl using 'password' is no longer working and not clear explaination how to migrate existing installation password to token based autentication** 

> Prior to version 1.19, the following strategy is also available:
> 
> Static Password File with password tokens and usernames stored in /var/snap/microk8s/current/credentials/basic_auth.csv
> https://microk8s.io/docs/ports#heading--auth

### The (temporary) Workaround

I use the following command (after I comment admin username & password in ~/.kube/config file) to use kubectl

> kubectl --token=<admin token from known_tokens.csv>  --kubeconfig=./config get all

**Comment by ktsakalozos** [comment]
Hi @jazarja,

Thank you for reporting this and for providing a workaround. With v1.19 release the basic authentication has been removed [1, 2]  from upstream Kubernetes. To prepare for this change for some months now we have been shipping new deployments with token auth only.

While upgrading existing deployments we attempt to re-write the `/var/snap/microk8s/current/credentials/client.config` file to use a token [3]. It is hard to say why this re-write did not work in your case, it might help if you attached the `microk8s.inspect` tarball.

If you already have a kubeconfig file that works you can point microk8s' kubectl to it by adding a line similar to `export KUBECONFIG=$SNAP_DATA/credentials/client.config` in `/var/snap/microk8s/current/args/kubectl-env` and/or you can even copy your kubeconfig file over `/var/snap/microk8s/current/credentials/client.config`. 

Also I suspect you have a long lasting non-ephemeral deployment. In such cases it is recommended you follow a channel using the `--channel` arguments eg `snap install microk8s --classic --channel=1.19`. This way you will not be affected by such breaking changes.


[1] https://kubernetes.io/docs/setup/release/notes/#no-really-you-must-read-this-before-you-upgrade
[2] https://github.com/kubernetes/kops/pull/8783
[3] https://github.com/ubuntu/microk8s/blob/master/snap/hooks/configure#L346

**Comment by sergiohinojosa** [comment]
Hi @jazarja  

thanks for the workaround! I spend quite some time yesterday trying to figure out how in the heck to make a simple API connection to a microk8s v.19 running on multipass. I have been running older versions and did not had an issue.

When I debuged the command and compared the one connecting successfully with what I had, I noticed that the header instead of `"Authorization: Bearer <masked>"` it was `"Authorization: Basic <masked>"`. So in order for the kubectl client to connect successfully in the user object just add the token with the password of the admin (of my microk8s.config). This will send the password as bearer token and it will connect successfully. 
If I want to connect with valid certificates then just add the external IP or domain (since I use magic domains such as nip.io) to the `/var/snap/microk8s/current/certs/csr.conf.template` or disable them on the client with `insecure-skip-tls-verify: true`.

@ktsakalozos I would be great to have some documentation or examples on how to access microk8s from a kubectl client from the outside (even if its not the most secure access). I know security is a big issue these days but a guide or some of the most common examples would be great for increasing adoption. Maybe having a public codelab space where the community can add step-by-step tutorials would also increase the adoption of microk8s. 

Well those were my 5 cents :)
