### ISSUE TITLE
Add nodes ip resolve to HA's api-server's /etc/hosts 

### ISSUE THREAD

**Issue by enderson-pan** [canonical/microk8s#1566]
Hi, 
After create the HA，I notice that when I use kubectl port-forward or exec to some container, if the container locates on other nodes rather than on api-server node, dns lookup fails. The message shows that:

```
kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443
error: error upgrading connection: error dialing backend: dial tcp: lookup machine5 on 127.0.0.53:53: server misbehaving
```

After some digging, I found that after microk8s join, the node only add mater's ip and itself's ip to the /etc/hosts, so lookup the hostname of other node would failed due to the config of the lan router. 

So I add all nodes to the /etc/file of the node which api-server is on.

So maybe add all nodes hostname automaticly to /etc/hosts would be nice.

Thanks in advance

**Comment by ktsakalozos** [comment]
I see the problem here @enderson-pan, thank you for reporting it.

I am a bit hesitant to edit the `/etc/hosts` file from the snap as part of the joining process. Apart from the obvious sync issues we may face editing files on the host works against the snap confinement we try to achieve. I think the first step should be to document the issue [1, 2] and even try to automate a check in the inspection script. If this becomes a common complain we should investigate how to resolve the issue in an automated way.

[1] https://microk8s.io/docs/troubleshooting#heading--common-issues
[2] https://microk8s.io/docs/clustering

**Comment by mbachari** [comment]
Definitely running into this issue as well, I run multi node cluster for my tests and noticed that DNS resolution was failing for any worker node. For example `kubectl logs <pod-not-on-master>` will fail with the below error similar to the above issue
```
Error from server: Get "https://worker1:10250/containerLogs/ingress/nginx-ingress-microk8s-controller-qvjs2/nginx-ingress-microk8s?follow=true": dial tcp: lookup worker1: Temporary failure in name resolution
```

**Comment by oivindoh** [comment]
@ktsakalozos any idea what would be the proper way to deal with this outside editing hosts directly? Facing this issue while trying to adopt microk8s.  Many edge scenarios will not have particularly functional DNS infrastructure to speak to, so I don't really see any other options.

**Comment by PAStheLoD** [comment]
The problem is that CoreDNS does not resolve the hostname of the nodes (and even though the feature was requested it was marked as WONTFIX basically), and thus there really isn't any service that knows it besides the k8s apiserver.

Editing the hosts file is not ideal, but at least can be done with this on each node:

```
microk8s kubectl get nodes -o wide | awk '{ print $6 " " $1 }' | tail -n +2 | grep -v $(hostname)  >> /etc/hosts
```


If your nodes going to change frequently, then probably you need to put something like this into a CRON script (or systemd timer unit). It's the same as the previous one-liner with before-after guard lines to be able to replace multiple lines.

```
perl -i -p0e 's/## microk8s nodes begin.*## microk8s nodes end//s' /etc/hosts
echo '## microk8s nodes begin' >> /etc/hosts
microk8s kubectl get nodes -o wide | awk '{ print $6 " " $1 }' | tail -n +2 | grep -v $(hostname)  >> /etc/hosts
echo '## microk8s nodes end' >> /etc/hosts
```

It's also possible to [somehow ](https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/) put all this into the Corefile of CoreDNS (which is basically in the coredns configmap in the kube-system NS), and use the in-cluster DNS service from the hosts, but it's left as exercise for the reader, because it seems even more fragile than manipulating the hosts file.

**Comment by upodroid** [comment]
This still a big problem which isn't documented at all on microk8s.io

Also this should be handled by the install process. I have been using RKE clusters and I don't see this problem.

```
ubuntu@k-one:~$ microk8s kubectl port-forward po/argocd-server-86f7f94488-2zntt 8080 -n argocd
error: error upgrading connection: error dialing backend: dial tcp: lookup k-three: Temporary failure in name resolution
ubuntu@k-one:~$ microk8s kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
k-three   Ready    <none>   42m   v1.21.1-3+ba118484dd39df
k-two     Ready    <none>   48m   v1.21.1-3+ba118484dd39df
k-one     Ready    <none>   56m   v1.21.1-3+ba118484dd39df
```

**Comment by mashkovd** [comment]
> The problem is that CoreDNS does not resolve the hostname of the nodes (and even though the feature was requested it was marked as WONTFIX basically), and thus there really isn't any service that knows it besides the k8s apiserver.
> 
> Editing the hosts file is not ideal, but at least can be done with this on each node:
> 
> ```
> microk8s kubectl get nodes -o wide | awk '{ print $6 " " $1 }' | tail -n +2 | grep -v $(hostname)  >> /etc/hosts
> ```
> 
> If your nodes going to change frequently, then probably you need to put something like this into a CRON script (or systemd timer unit). It's the same as the previous one-liner with before-after guard lines to be able to replace multiple lines.
> 
> ```
> perl -i -p0e 's/## microk8s nodes begin.*## microk8s nodes end//s' /etc/hosts
> echo '## microk8s nodes begin' >> /etc/hosts
> microk8s kubectl get nodes -o wide | awk '{ print $6 " " $1 }' | tail -n +2 | grep -v $(hostname)  >> /etc/hosts
> echo '## microk8s nodes end' >> /etc/hosts
> ```
> 
> It's also possible to [somehow ](https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/) put all this into the Corefile of CoreDNS (which is basically in the coredns configmap in the kube-system NS), and use the in-cluster DNS service from the hosts, but it's left as exercise for the reader, because it seems even more fragile than manipulating the hosts file.

it's perfect solution. It should be better automatic add hosts notes like this after join node

*.*.*.155 master-1
*.*.*.156 node-1
*.*.*.157 node-2

**Comment by tobiasmuehl** [comment]
@PAStheLoD Thanks for your script. I've made some modifications:

- Prevent adding a new line everytime the cronjob runs
- Work on a copy of the file so there's no race condition while the `microk8s kubectl` command runs (it's slow on my machine, definitely multiple milliseconds)

```sh
cp /etc/hosts /etc/hosts.new
perl -i -p0e 's/## microk8s nodes begin.*## microk8s nodes end\n//s' /etc/hosts.new
echo '## microk8s nodes begin' >> /etc/hosts.new
sudo microk8s kubectl get nodes -o wide | awk '{ print $6 " " $1 }' | tail -n +2 | grep -v $(hostname)  >> /etc/hosts.new
echo '## microk8s nodes end' >> /etc/hosts.new
mv -f /etc/hosts.new /etc/hosts
```

**Comment by ProjectInitiative** [comment]
@ktsakalozos, as mentioned by @upodroid, this issue isn't well documented as a caveat during the installation process. It can be incredibly confusing for those trying out different "one and done" solutions out there. The folks over at Rancher (RKE, k3s, etc) include this functionality by default. If it is truly something that should not be added to the snap, then at least there should be some documentation explaining why it goes against best practice to include this behavior by default. 

Otherwise (my experience included) users trying out different k8s distributions will be wonder why something is "broken" with no concrete answer to why the behavior is different from other competitive "one and done" solutions.

Thanks

**Comment by tobiasmuehl** [comment]
To give some weight to this issue, it is one of only 2 reasons why I migrated everything from microk8s to k3s
