### ISSUE TITLE
VPN reset causes all pods to become not ready -> Unknown -> Ready

### ISSUE THREAD

**Issue by Purneau** [canonical/microk8s#2096]
We are running MicroK8s but our applications need a VPN to securely connect with each other. 
For this in some situations we have an Ubuntu VM with an OpenVPN connection active. On this VM Microk8s is installed.

However, if something changes in this VPN (like a reconnect) the pods in our cluster first become not ready and after a few minutes their status changes into Unknown. After approximately 20-30 minutes the issue slowly resolves itself and all pods become Ready again (and the application accessible). 

Is this a known and/or expected issue? 

I tried to run a `microk8s inspect` during this issue, but it takes very long to run. The result is attached.
[inspection-report-20210316_113756.tar.zip](https://github.com/ubuntu/microk8s/files/6148584/inspection-report-20210316_113756.tar.zip)

Thanks for your help

**Comment by AndrzejOlender** [comment]
I have the same problem. OpenVPN connection/disconnection and problems with Unknown.

**Comment by ktsakalozos** [comment]
Hi @Purneau @AndrzejOlender, this behavior is partially expected. A new interface comes up and microk8s needs to reconfigure it self so it takes into account the change. The 20-30 minutes however is too long! I need to spend more time on that.

One way to stop this reconfiguration is to edit `/var/snap/microk8s/current/args/kube-apiserver` and set either the `--advertise-address` or the `--bind-address` according to [1] and then restart microk8s one last time with `microk8s.stop; microk8s.start`.

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by Purneau** [comment]
Hi @ktsakalozos, please forgive my ignorance, but based on the tarball: what would be the IP that I would need to set as `--advertise-address` or the `--bind-address` to minimise this behaviour?

**Comment by ktsakalozos** [comment]
@Purneau the most straight forward is to specify the interfaces where the API server should be available from. You can use the `--bind-address` for that. You can see the available interfaces with `ip a`.

**Comment by devZer0** [comment]
i think that behaviour cab be expected, imho it's how the code in microk8s works. by chance i had a look on that part today and found this ticket while searching this tracker for apiservice-kicker, because i think it does not handle things efficiently (for example it's rebuilding a csr.conf to compare if ip adresses did change, which could be easier be done and without constantly writing to the disk in short intervals, i.e. why aren't ip adresses being compared but something generated from it?)

it looks that apiservice-kicker will restart services when it detects changed certs, and certs will change, when there is ip adress change on the server. imho, that will also trigger , when an additional ip adress appears or disappears, which should apply to temporary vpn connection...

have a look
```
/snap/microk8s/2074/apiservice-kicker

        csr_modified="$(produce_certs)"
        if [[ "$csr_modified" -eq "1" ]];
        then
            echo "CSR change detected. Reconfiguring the kube-apiserver"
            rm -rf .srl
            snapctl restart microk8s.daemon-etcd
            snapctl restart microk8s.daemon-containerd
            snapctl restart microk8s.daemon-apiserver
            snapctl restart microk8s.daemon-proxy
            snapctl restart microk8s.daemon-kubelet
            restart_attempt=$[$restart_attempt+1]
            

/snap/microk8s/current/actions/common/utils.sh           


get_ips() {
    local IP_ADDR="$($SNAP/bin/hostname -I)"
    if [[ -z "$IP_ADDR" ]]
    then
        echo "none"
    else
        if $SNAP/sbin/ifconfig cni0 &> /dev/null
        then
          CNI_IP="$($SNAP/sbin/ip -o -4 addr list cni0 | $SNAP/usr/bin/gawk '{print $4}' | $SNAP/usr/bin/cut -d/ -f1 | head -1)"
          local ips="";
          for ip in $IP_ADDR
          do
            [ "$ip" != "$CNI_IP" ] && ips+="${ips:+ }$ip";
          done
          IP_ADDR="$ips"
        fi
        echo "${IP_ADDR}"
    fi
}

 
            render_csr_conf() {
    # Render csr.conf.template to csr.conf.rendered

    local IP_ADDRESSES="$(get_ips)"

    cp ${SNAP_DATA}/certs/csr.conf.template ${SNAP_DATA}/certs/csr.conf.rendered
    if ! [ "$IP_ADDRESSES" == "127.0.0.1" ] && ! [ "$IP_ADDRESSES" == "none" ]
    then
        local ips='' sep=''
        local -i i=3
        for IP_ADDR in $(echo "$IP_ADDRESSES"); do
            ips+="${sep}IP.$((i++)) = ${IP_ADDR}"
            sep='\n'
        done
        "$SNAP/bin/sed" -i "s/#MOREIPS/${ips}/g" ${SNAP_DATA}/certs/csr.conf.rendered
    else
        "$SNAP/bin/sed" -i 's/#MOREIPS//g' ${SNAP_DATA}/certs/csr.conf.rendered
    fi
}


man hostname 

 -I, --all-ip-addresses
              Display all network addresses of the host. This option enumerates all configured addresses on all network interfaces.
              
```

**Comment by devZer0** [comment]
also see https://github.com/ubuntu/microk8s/issues/1943

**Comment by kevin-david** [comment]
I also have this problem but the pods never come back - they are stuck in "Unknown". in my case, my internet connection seems to be dying overnight leading to pod "failure"

i'm also using DHCP with the host machine, and it's getting the same IPv4 address but I assume the v6 address is changing. 

this network reset also causes pod restart to fail (image pull just hangs) unless i stop/start microk8s afterwards. I reported this behavior over here: https://github.com/ubuntu/microk8s/issues/1113#issuecomment-771790841

here is another inspection report from this after the pods got stuck in "unknown" status:
[inspection-report-20210407_123827.tar.gz](https://github.com/ubuntu/microk8s/files/6271748/inspection-report-20210407_123827.tar.gz)

**Comment by devZer0** [comment]
recent activity because stale bots suck

**Comment by devZer0** [comment]
thank you for the in-depth explanation. very valuable/appreciated !

the problem is, i have seen to many issue tracker where issues getting closed by stale bots instead of being looked at or resolved.  

this is frustrating for users reporting issues and for all contributors, which add information to the issues. they are getting scared away with this.

that's the reason why i started adding anti-stale-bot-posts.

i know that developer need to keep focus, but i think issue reports should never get closed because of inactivity.

**Comment by neoaggelos** [comment]
I agree with you in general. However, given the number of duplicates issues (for example, a recent one being https://github.com/canonical/microk8s/issues/3575), it would make sense to keep the issues that are "actionable", or the ones where the original poster is coming back with more information and giving feedback so that the issue is resolved.

To be honest, I very much agree with your sentiment: The measure of success for a project is not the number of closed issues, but rather the engagement with the community and the resolution of ongoing problems users are having.

**Comment by neoaggelos** [comment]
Hi @D5Sammy 

Do you also experience any workloads restarting when that happens? Can you see if the following fixes your problem:

```
sudo touch /var/snap/microk8s/current/var/lock/no-cert-reissue
```
