### ISSUE TITLE
Kubeflow installation stuck with waited for Pod operator to come up

### ISSUE THREAD

**Issue by topprwk** [canonical/microk8s#2145]
After run microk8s enable kubeflow, I got a warnings like this 

```
ubuntu@microk8s-vm:~$ microk8s enable kubeflow 
Kubeflow recommends at least 8 GB of free memory.
Use `--ignore-min-mem`if you'd like to proceed anyways.
```

Then I following the suggestion but it stuck with waited for Pod operator to come up as following log
```
microk8s enable kubeflow --ignore-min-mem
Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...
Addon setup complete. Checking connectivity...
Bootstrapping...
Bootstrap complete.
Successfully bootstrapped, deploying...
Kubeflow deployed.
Waiting for operator pods to become ready.
Waited 0s for operator pods to come up, 27 remaining.
Waited 15s for operator pods to come up, 27 remaining.
Waited 30s for operator pods to come up, 27 remaining.
Waited 45s for operator pods to come up, 27 remaining.
Waited 60s for operator pods to come up, 27 remaining.
Waited 75s for operator pods to come up, 27 remaining.
Waited 90s for operator pods to come up, 27 remaining.
Waited 105s for operator pods to come up, 26 remaining.
Waited 120s for operator pods to come up, 25 remaining.
Waited 135s for operator pods to come up, 25 remaining.
Waited 150s for operator pods to come up, 25 remaining.
Waited 165s for operator pods to come up, 25 remaining.
Waited 180s for operator pods to come up, 28 remaining.
Waited 195s for operator pods to come up, 29 remaining.
Waited 210s for operator pods to come up, 29 remaining.
Waited 225s for operator pods to come up, 30 remaining.
Waited 240s for operator pods to come up, 30 remaining.
Waited 255s for operator pods to come up, 29 remaining.
Waited 270s for operator pods to come up, 26 remaining.
Waited 285s for operator pods to come up, 25 remaining.
Waited 300s for operator pods to come up, 25 remaining.
Waited 315s for operator pods to come up, 28 remaining.
Waited 330s for operator pods to come up, 28 remaining.
Waited 345s for operator pods to come up, 29 remaining.
Waited 360s for operator pods to come up, 29 remaining.
Waited 375s for operator pods to come up, 29 remaining.
Waited 390s for operator pods to come up, 27 remaining.
Waited 405s for operator pods to come up, 26 remaining.
Waited 420s for operator pods to come up, 28 remaining.
Waited 435s for operator pods to come up, 26 remaining.
Waited 450s for operator pods to come up, 25 remain
```

and it's like this for whole day. How can I solve this?? Is it about my MacBook RAM?? 

Thanks guy

**Comment by ktsakalozos** [comment]
@joedborg is it possible to set the memory size of the multipass VM when installing on Mac?

@knkski @topprwk maybe you would want to try `microk8s enable kubelfow --bundle lite` ?

**Comment by joedborg** [comment]
Hi @topprwk out of interest, how much memory does your Mac have?  You can check what's holding the deployment up by running `microk8s kubectl get all --all-namespaces` in a different Terminal tab or window.

**Comment by HWiese1980** [comment]
So a bunch of such issues still remain open. I'll try and add myself to the queue of people waiting for an answer. 

My PC that I'm trying to run Kubeflow on is a Windows system with 32G of RAM, of which 8G are assigned to the MicroK8S VM. More doesn't work because I'm getting a "not enough resources to allocate memory" error. 

Now with 8G I've tried to enable Kubeflow in MicroK8S VM but it's been stuck at "5 remaining" for a couple hours now. I haven't tried the lite bundle yet. It's the next thing I'll try. 

I've been yak shaving the last couple of days to get Kubeflow running. I've tried it on two systems now, a MacBook (16G RAM), and a PC (32G RAM) using multiple approaches, MicroK8S, kfctl, manually installing the manifests. To no avail so far. There's always some road block I'm running into. 

I'm pretty new to Kubernetes. I might not have understood everything.
