### ISSUE TITLE
Cannot uninstall on Windows

### ISSUE THREAD

**Issue by larsskj** [canonical/microk8s#2303]
>>> Please run `microk8s inspect` and attach the generated tarball to this issue.

I cannot. Sorry.

My microk8s install on Windows failed miserably so I want to uninstall and start over. Unfortunately, the uninstaller doesn't work on my machine running Windows 10 Enterprise 1909.

When I go to "Apps & features", select "MicroK8s 2.1.0" and click "Uninstall" - the only result after a short while is a dialogue stating

```
C:\Program Files\MicroK8s\uninstall.exe
A referral was returned from the server.
```

I deleted the microk8s-vm using Multipass. If I try to reinstall it, I get the following error:

```
C:\Users\kilroy>microk8s install
Launched: microk8s-vm
ping: snapcraft.io: Temporary failure in name resolution
An error occurred when trying to execute 'sudo ping -c 1 snapcraft.io' with 'multipass': returned exit code 2.

```

**Comment by joedborg** [comment]
Hi @larsskj,

Thanks for reaching out.  I'm fairly sure (but not certain) that `A referral was returned from the server` comes when Windows doesn't have admin rights in order to uninstall, so maybe running that uninstall script again within an Administrator PS / cmd would work?

The failure on the install would point towards a networking issue, are you behind a VPN / Firewall?  This might also help https://multipass.run/docs/troubleshooting-networking-on-windows

Thanks,
Joe

**Comment by larsskj** [comment]
Sorry for the late reply: Having been away from the office and haven't had the possibility to test this theory.

Now I have - and you're not right: It fails in exactly the same way when I'm logged in as a Windows administrator. Still cannot uninstall.

And now I'm running on the corporate network and a proper NIC. No WiFi, no VPN - nothing to clutter the picture.

Best regards,
Lars

**Comment by larsskj** [comment]
Investigating a little further, I now have a new class of problems. Still cannot uninstall, but at least it claims to be installed now:

`C:\Users\kilroy>microk8s install
MicroK8s is up and running. See the available commands with ``microk8s --help``.`

But trying to inspect:

`C:\Users\kilroy>microk8s inspect
sudo: microk8s.inspect: command not found
An error occurred when trying to execute 'sudo microk8s.inspect' with 'multipass': returned exit code 1.`
