### ISSUE TITLE
Ingress giving 503, cannot resolve

### ISSUE THREAD

**Issue by dleske** [canonical/microk8s#2331]
I had this trouble in 1.19 and upgrading to 1.21 hasn't solved the issue.

I have a MicroK8s cluster of 3 nodes fronted by a reverse proxy.  The intention is to have the reverse proxy load balance to the three nodes.  These four VMs are on a private network and the RP (obvs) has a public-facing address.  I am using a similar setup _without_ Ingress, where each backend points to a k8s node and the port of a NodePort service, but would like to make use of Ingress more friendly routing and so make use of the incoming hostname.

I have deployed a test app `fake-app` in the `fake-app` namespace.  It is a basic Nginx image with content from a configMap.  I have exposed this deployment with a service.  From any node in the cluster I can contact the service:

```
$ curl http://localhost:32001
<html>
<body>
<p>This is the FaKE APP.  Awwww yeah.</p>
</body>
</html>
```

I have the following Ingress set up:

```
$ kubectl -n fake-app get ingress -o yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"fake-app-ingress","namespace":"fake-app"},"spec":{"ingressClassName":"public","rules":[{"host":"fake-app.go.computecanada.org"},{"http":{"paths":[{"backend":{"service":{"name":"fake-app","port":{"number":32001}}},"path":"/","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2021-06-09T23:09:40Z"
    generation: 6
    name: fake-app-ingress
    namespace: fake-app
    resourceVersion: "267245"
    selfLink: /apis/networking.k8s.io/v1/namespaces/fake-app/ingresses/fake-app-ingress
    uid: eab3353f-6ce6-4f98-af9c-80bd37f74e6e
  spec:
    ingressClassName: public
    rules:
    - host: fake-app.go.example.org
    - http:
        paths:
        - backend:
            service:
              name: fake-app
              port:
                number: 32001
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 127.0.0.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

But if I try to get at the app through the Ingress:

```
$ curl --insecure --resolve 'fake-app.go.example.org:443:127.0.0.1' https://localhost
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

(Oddly--using the simpler `curl -H 'Host: fake-app.go.example.org' localhost` I get a 404 in 1.21, but got the same 503 on 1.19.)

I've tried to define the backend as:

```
spec:
  ingressClassName: public
  rules:
  - host: fake-app.go.example.org
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          resource:
            kind: service
            name: fake-app
```

But the ingress would not be able to find the service, which would fail with this in the ingress controller's pod logs:

```
W0611 14:30:53.276450       6 controller.go:889] Error obtaining Endpoints for Service "fake-app/": no object matching key "fake-app/" in local store
```

I've changed that to:

```
...
          service:
            name: fake-app
            port:
              number: 32001
```

...but I still get the 503:

```
I0611 15:57:22.883257       6 controller.go:146] "Configuration changes detected, backend reload required"
I0611 15:57:22.996255       6 controller.go:163] "Backend successfully reloaded"
I0611 15:57:22.996832       6 event.go:282] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ingress", Name:"nginx-ingress-microk8s-controller-c5896", UID:"25c37ab5-469d-4f15-be91-846fc9456107", APIVersion:"v1", ResourceVersion:"11127", FieldPath:""}): type: 'Normal' reason: 'RELOAD' NGINX reload triggered due to a change in configuration
192.168.113.8 - - [11/Jun/2021:15:57:27 +0000] "GET / HTTP/2.0" 503 190 "-" "curl/7.58.0" 26 0.000 [fake-app-fake-app-32001] [] - - - - 09473dd4faeca7be90166b46fa1065b8
```

I notice that the 404 are from not finding the default backend.  Which, in the 1.19 attempt, worked: attempts to reach an unmapped host would get a "There is no app defined at this address" sort of message.  So some part of the Ingress appears to be working in that it recognizes the host and tries to do something with it.  I just can't figure out where it's going off the rails.

This is on an OpenStack cluster without any LoadBalancer resource, but I can't understand if/why that would be an issue.  It's my understanding the Ingress works by listening on ports 80/443 (I'm not doing TCP/UDP apart from web) on each node, and routes requests according to the request's host and path, so going to a k8s node and querying localhost on these ports should work.  netstat shows it's Ingress listening on those ports.

I obviously may have missed something but I've read k8s and microk8s documentation on ingress and searched for similar reports.  Every issue I've found referencing a 503 response has been due to a service mapping issue or an unexposed deployment.  I don't think that's the case here.

Please let me know if further information would be helpful.

Inspection report included: [inspection-report-20210611_160014.tar.gz](https://github.com/ubuntu/microk8s/files/6639821/inspection-report-20210611_160014.tar.gz)

**Comment by nnsense** [comment]
Hi, I think I've hit the same issue, unfortunately I came here to post my issue and I've found yours. Just to check can you please post the output you get from
```
mk -n ingress describe daemonset.apps/nginx-ingress-microk8s-controller
```

In my case, after a clean install (no changes whatsoever), my readness is failing because its config is wrong (no hostname, as you can see):
```
 [..]
   Readiness:  http-get http://:10254/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
 [..]
```

I'm going to post this now

Thanks

**Comment by neoaggelos** [comment]
Looking at the original issue, it looks like an issue with the ingress definition rather than a bug in MicroK8s. For example, I see 

```yaml
    rules:
    - host: fake-app.go.example.org
    - http:
        paths:
        - backend:
            service:
              name: fake-app
              port:
                number: 32001
          path: /
          pathType: Prefix
```

I think it should instead be:

```yaml
    rules:
    - host: fake-app.go.example.org
      http:
        paths:
        - backend:
            service:
              name: fake-app
              port:
                number: 32001
          path: /
          pathType: Prefix
```

@Mbd06b can you share your ingress definition, or at least a minimal manifest that causes the error you are seeing? Thanks!

**Comment by Mbd06b** [comment]
Hey I figured out my issue. 
My ingress was correct, and my Endpoint worked, those were fine. 
 
In my unique case I am on a journey to migrate incrementally to microk8s, but I still have a lot of locally hosted applications, which is the type of setup not well documented by tutorials.  I for a long time I've served apps with an nginx running on the host machine aka the  "master node", and its a big switchover to serving the same apps via the nginx-ingresses, since nginx/ingress don't run nicely together on the same machine since they both want the 80:443 port. 

The problem I discovered is that I had an an additional app: selector as part of my Service spec.
So in Service documentation the usually have an "app" selector, which ensures traffic is delivered to the running application pods in a cluster, but in my case, I wanted to be running a "headless-service" which routes traffic back to a specific Endpoint object which represents my host-machine (and not a cluster pod).  

The service was seeing an "app: jenkins" selector, was in conflict with the port spec on the same service, and ending up in a 503 state.  There wasn't much in terms of logs to help identify the disconnect.   

I also should note, if I had been routing to jenkins actually running in the cluster, my service definition would have probably been fine, which is why I  was having problems trying to identify what exactly was wrong with my configuration. 

Anyway.. here's the working configuration. 

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: jenkins-ingress
 namespace: host-services
 annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: public
spec:
 tls:
 - hosts:
   - jenkins.example.com
   secretName: jenkins-ingress-tls
 rules:
 - host: jenkins.ethosengine.com
   http:
     paths:
     - backend:
         service:
           name: jenkins
           port:
             number: 80
       path: /
       pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: host-services
spec:
  ports:
    - name: jenkins
      protocol: TCP
      port: 80
      targetPort: 6000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins
subsets:
- addresses:
  - ip: 10.0.1.1 #host-access microk8s address
  ports:
  - name: jenkins
    port: 6000
    protocol: TCP`
