### ISSUE TITLE
microk8s dbctl backup panics: etcdwrapper: key not found

### ISSUE THREAD

**Issue by npiganeau** [canonical/microk8s#2339]
When running `microk8s.dbctl backup` on a 3 node HA cluster (v1.20.7), I get the following error:

```
root@node13:~# microk8s.dbctl backup 
Backing up the datastore
INFO[0000] mode: backup-dqlite, endpoint: unix:///var/snap/microk8s/current/var/kubernetes/backend/kine.sock, dir: /tmp/tmpyfpmjp9c/backup-2021-06-15-10-25-47 
panic: etcdwrapper: key not found

goroutine 1 [running]:
main.check(...)
	/build/microk8s/parts/migrator/build/main.go:75
main.backup_dqlite(0xc36b28, 0x42, 0x7ffcdfc55396, 0x2b, 0x0, 0x0)
	/build/microk8s/parts/migrator/build/main.go:182 +0x887
main.run(0xc0000d0dc0)
	/build/microk8s/parts/migrator/build/main.go:283 +0x606
github.com/urfave/cli.HandleAction(0xb22fa0, 0xc441e8, 0xc0000d0dc0, 0xc0000d0dc0, 0x0)
	/build/microk8s/parts/migrator/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:528 +0x58
github.com/urfave/cli.(*App).Run(0xc0000d6380, 0xc0000320a0, 0x5, 0x5, 0x0, 0x0)
	/build/microk8s/parts/migrator/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x655
main.main()
	/build/microk8s/parts/migrator/build/main.go:68 +0x4f6
Backup process failed. 2
```

Here is the inspection report of my cluster:

[inspection-report-20210615_102327.tar.gz](https://github.com/ubuntu/microk8s/files/6654038/inspection-report-20210615_102327.tar.gz)

Thank you

**Comment by k402xxxcenxxx** [comment]
same issue found in v1.23.0

**Comment by jdewald** [comment]
Glad I found this issue, as I was about to create the same. I had been running a nightly `microk8s dbctl backup` on a non-HA cluster for probably 6 months or so. I recently got my cluster up to 3 nodes and it went into HA mode. Within a few days the backup begin failing with the `etcdwrapper: key not found` error. 

One bit of additional info is that the key that's not found corresponds to the pod for a frequently running `CronJob` CRD. So perhaps a race condition somewhere creating the inconsistency. I've confirmed that `Pod` for the missing key isn't something that's visible in the cluster currently. 

The captured output corresponding to the issue:

`time="2023-05-01T00:02:00-07:00" level=fatal msg="couldn't get key /registry/pods/<namespace>/<cj>-cron-28048730-pksls: etcdwrapper: key not found"`

**Comment by neoaggelos** [comment]
Hi @jdewald thanks for raising this, looks like it was missed with the stale bot.

Indeed, there is an issue with the dbctl command when a key is deleted most likely _while_ the backup operation is on the way, causing the error message that you have observed.

The correct way to handle this would be to improve the dbctl command to take the database revision into account while backing up the cluster. Reopening so that we deal with it.

**Comment by jdewald** [comment]
> ...
> Indeed, there is an issue with the dbctl command when a key is deleted most likely _while_ the backup operation is on the way, causing the error message that you have observed.
> 

Based on the above, I just confirmed that the actual key that's missing varies on each run (I hadn't been paying attention and assumed it was always the same one since it was the same frequently-running `CronJob`).

So I do at least know how to work around the issue a bit if needed until fix is available!
