### ISSUE TITLE
How to change datastore master nodes ip address

### ISSUE THREAD

**Issue by hagna** [canonical/microk8s#2511]
```
$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 10.x.x.x:19001
  datastore standby nodes: none
```

netstat says kubelite is listening on 10.x.x.x:19001, but I want it to listen on 192.168.x.x:19001 interface instead. 

Will microk8s allow a change from 10.x.x.x to 192.168.x.x or would it be easier to start over?

Also tried this https://github.com/ubuntu/microk8s/issues/2402#issuecomment-875071474 but can-reach=192.168.x.x is true for 10.x.x.x, so maybe that's the problem?

**Comment by ktsakalozos** [comment]
Hi @hagna, the first node you get with a `snap install microk8s` does not listen on a specific interface. As soon as you join a second node the two nodes assume the cluster is formed using the network interface they are reachable from. Since your node reports that the master is at 10.x..x.x at some point in the past there was a second node on that network. I assume now you want to add a node that is on the 192.168.x.x network, right?

At this point the easiest way forward is to start over. Maybe @MathieuBordere knows of a way to safely update the IP dqlite is listening on.

**Comment by MathieuBordere** [comment]
@ktsakalozos The dqlite `.reconfigure` command could help in this case, it's not yet in your current snaps I think, so not really a help for @hagna, but you could already try it out to see if it can solve cases like this.
