### ISSUE TITLE
Digitally signing microk8s binaries for windows

### ISSUE THREAD

**Issue by wtfacoconut** [canonical/microk8s#2627]
This is an enhancement request.

Would it be possible to request that the installer and binaries be digitally signed?

MicroK8s is getting flagged as malware by things like enterprise AVs and endpoint protection, partially because nothing is digitally signed.

I uploaded the "microk8s.exe" binary that gets installed in to VirusTotal and got the following results.

![image](https://user-images.githubusercontent.com/5297545/135960719-863fa630-ceff-43ae-a640-fc3844047440.png)

![image](https://user-images.githubusercontent.com/5297545/135960738-a9dd763d-d629-44bb-a9c8-5dfb43dd39cf.png)

![image](https://user-images.githubusercontent.com/5297545/135960774-5c327525-d476-4ff3-9a84-9eeb6aef8cc2.png)

![image](https://user-images.githubusercontent.com/5297545/135960819-c7b71e4c-6984-4b4e-9179-838cbb81580c.png)

![image](https://user-images.githubusercontent.com/5297545/135960835-00d8ac73-6524-48fa-b836-1d262b06c031.png)

**Comment by wtfacoconut** [comment]
Hey @joedborg , what I uploaded was the `microk8s.exe` file what gets installed. Not the installer itself.

Just to be more specific, from my host, I uploaded the following to virus total:
`C:\Program Files\MicroK8s\microk8s.exe`

**Comment by joedborg** [comment]
Hey @wtfacoconut,

I've just re-run and get similar results.  I'm not sure the issue here is signing, I think the issue will be that some of the Python libraries we use trigger the malware alarms as they might have been used in malicious software.  We'll need to think about how to address this.

![Screenshot 2021-11-01 112605](https://user-images.githubusercontent.com/1426404/139700243-23d454bb-22b5-49ef-8345-cd400e182bb8.png)
