### ISSUE TITLE
Inter pod communication on Fedora 34

### ISSUE THREAD

**Issue by d-rk** [canonical/microk8s#2636]
I just ran into an issue using microk8s on fedora 34.
pod to pod communication was not working.

I was able to resolve the issue by doing the following:
```
sudo firewall-cmd --zone=FedoraWorkstation --add-masquerade --permanent
sudo firewall-cmd --reload
```

My question is: is there a place to document stuff like this?

**Comment by random-dwi** [comment]
Hi @ktsakalozos,
it is hard for me to test this with other fedora versions.
I recently updated to Fedora 35 and ran into the same issue again and the fix above did not work.

Here is a brief summary how to diagnose issues with firewall-cmd:

```sh
# get the subnet cidr the pods are using
SUBNET=`cat /var/snap/microk8s/current/args/cni-network/cni.yaml | grep CALICO_IPV4POOL_CIDR -a1 | tail -n1 | grep -oP '[\d\./]+' 
echo $SUBNET

# enable logging of denied packets
sudo firewall-cmd --set-log-denied=all
sudo firewall-cmd --reload

# e.g. restart a pod and check for denied packets with dmesg
# (look for packets having an IP from the SUBNET above as SRC)
dmesg | grep -i REJECT

# if you see packets being rejected create a dedicated zone for microk8s:
sudo firewall-cmd --permanent --new-zone=microk8s-cluster
sudo firewall-cmd --permanent --zone=microk8s-cluster --set-target=ACCEPT
sudo firewall-cmd --permanent --zone=microk8s-cluster --add-source=$SUBNET
sudo firewall-cmd --reload

# finally reset the logging
sudo firewall-cmd --set-log-denied=off
sudo firewall-cmd --reload
```

Since this solution is not restricted to the `FedoraWorkstation` zone, it can be applied more generally.

From the options you gave I would assume the second (https://microk8s.io/docs/troubleshooting#heading--common-issues) would be a good place to document this.

Can I submit a PR somewhere for that?

**Comment by ktsakalozos** [comment]
> Can I submit a PR somewhere for that?

That would be great. This doc page is a forum post [1]. You could submit your "patch" as a reply to that post and we will update the main post. We would need a title, a problem description and the solution.

Many thanks 

[1] https://discuss.kubernetes.io/t/troubleshooting/11267
