### ISSUE TITLE
Reliability problem with microk8s v1.21.6

### ISSUE THREAD

**Issue by djjudas21** [canonical/microk8s#2723]
Please run `microk8s inspect` and attach the generated tarball to this issue.

[inspection-report-20211114_150556.tar.gz](https://github.com/ubuntu/microk8s/files/7534021/inspection-report-20211114_150556.tar.gz)

My cluster on the `1.21/stable` channel got `v1.21.6 (2646)` last night. I've experienced unreliability with the cluster since, and I think the problem is due to kubelite. Looks like it crashes periodically and so I have rolling unavailability of the apiserver and this is causing lots of pods in `Unknown` state. I think there may also be a problem with networking as some of my Services are unavailable even though the Pods are up. I ran the inspection report on a node where kubelite seems completely dead but on other nodes I can't even run `microk8s status` because it just times out.

I'm trying to gather information on this but I don't know much (anything) about kubelite. Any help appreciated, thanks.

**Comment by ktsakalozos** [comment]
Hi @djjudas21 kubelite is the service that starts all the kubernetes processes. Looking at its logs (`journalctl -fu snap.microk8s.daemon-kubelite`) I see the datastore stressed (adding @MathieuBordere in case he sees anything specific). There are requests taking too long to complete (even more than 10 secs) and eventually k8s is giving up with:
```
Nov 14 14:22:50 kube01 microk8s.daemon-kubelite[3053096]: I1114 14:22:50.150269 3053096 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
Nov 14 14:22:50 kube01 microk8s.daemon-kubelite[3053096]: F1114 14:22:50.151126 3053096 server.go:205] leaderelection lost
``` 

This is most often the result of I/O (and in particular write) heavy processes competing for disk bandwidth. 

Also in the `dmesg` logs I see a log of incidents where the kernel had to kill processes because it was running out of memory.

Is there a way to reduce some of the load the node is called to serve? 

Something you could try is to increase the controller and scheduler lease time in hope that the respective leaders will eventually get their lease updated. In the files `/var/snap/microk8s/current/args/kube-controller-manager` and `/var/snap/microk8s/current/args/kube-scheduler` there are two arguments
```
--leader-elect-lease-duration=60s
--leader-elect-renew-deadline=30s
``` 
Have a look a [1] for the full description of the election configuration options.

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

**Comment by MathieuBordere** [comment]
Don't see anything obvious w.r.t. dqlite in the logs.

**Comment by djjudas21** [comment]
Hmm, I wasn't aware that memory was a problem on this node. Metrics for the node show approximately 50% memory usage and the nodes each have 8GB.
