### ISSUE TITLE
Feature request: Add whereabouts IPAM for use with Multus

### ISSUE THREAD

**Issue by antevens** [canonical/microk8s#2786]
When using multus for advanced networking it would be very nice to have a plugin for the ability to use Whereabouts https://github.com/k8snetworkplumbingwg/whereabouts for multi-node setups.

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @antevens

**Comment by mathiasbrito** [comment]
Any update one that, If I use host-local with community Multus, it works fine, but if I change IPAM to `whereabouts`, I get an error saying that the configuration file for the name of the network (e.g. home-network) was not found. 

In order to reproduce you just need to, after installing whereabouts, change the ipam plugin name to `whereabouts`

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "951b1d5abffffdc8cf3e131283120df2b9f4ff522ec6ee65bf757b6b3c4a8440": plugin type="multus" name="multus-cni-network" failed (add): [default/multus-alpine/abd5413f-aee5-4f2d-b9be-77da9c9acffb:home-network]: error adding container to network "home-network": config file not found
```
