### ISSUE TITLE
microk8s enable gpu -- daemonset fails to initialize

### ISSUE THREAD

**Issue by ZacBlanco** [canonical/microk8s#2902]
I have a cluster with 6 nodes, two of them have GPUs. I want to be able to eventually schedule some GPU applications to those specific nodes. After running `microk8s enable gpu` I notice all of the pods in the `gpu-operator-resources` namespace are stuck in the `Init` phase and have the following error when running `kubectl -n gpu-operator-resources describe po <pod name>`

All nodes are running Ubuntu Server 20.04

```
Events:
  Type     Reason                  Age               From               Message
  ----     ------                  ----              ----               -------
  Normal   Scheduled               65s               default-scheduler  Successfully assigned gpu-operator-resources/nvidia-device-plugin-daemonset-k8mrg to <host>
  Warning  FailedCreatePodSandBox  3s (x6 over 65s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured
```
I couldn't find any information about this particular error in the microk8s documentation. Based on some threads a while ago ([here](https://github.com/ubuntu/microk8s/issues/448), and [here](https://discuss.kubernetes.io/t/add-on-gpu/11286)) it seems like it shouldn't be necessary to update the docker daemon runtimes with the "nvidia" one because microk8s is supposed to be using containerd?

I'm just looking for some guidance to solve this issue and also help update the documentation if necessary. 

[inspection-report-20220204_183201.tar.gz](https://github.com/ubuntu/microk8s/files/8005385/inspection-report-20220204_183201.tar.gz)

P.S.: microk8s is great! Thanks for making such a great piece of software :smile:

**Comment by wally416** [comment]
@ZacBlanco I'm in the same boat.  It isn't a straight forward process, but CUDA never is.   This document has some tidbits that I'm trying right now:

https://discuss.kubernetes.io/t/my-adventures-with-microk8s-to-enable-gpu-and-use-mig-on-a-dgx-a100/15366

One key piece I didn't realize is that you don't want the nvidia drivers loaded before the gpu addon runs.  I guess it needs to do that part for you?

**Comment by wally416** [comment]
@ZacBlanco but if you read the add on source code, you see that it seems try to handle the case that the drivers are already loaded:  https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.gpu.sh

anyways, not much help but wanted to share the threads i'm pulling on since we are in the same situation

may the CUDA gods be with you

**Comment by wally416** [comment]
@ZacBlanco i just spent a few hours debugging my gpu add-on enable, and this was my issue:

  https://github.com/ubuntu/microk8s/issues/2662

cgroups2 needed to be disabled

**Comment by LukeekuL** [comment]
Hello @ZacBlanco, I have a similar issue with my cluster (mk8s v1.23, gpu-operator v1.8.2) where the master node does not have a GPU. I've noticed that if I enable the add-on from a node that has a GPUs the daemonset eventually succeeds. For this to work you cannot use the <code>--worker</code> flag while joining new nodes since this will disable the control plane on that node and force you to enable the add-on from (in my case) the master node. I hope this will help you. Nevertheless, this seems to be a bug because I can not use the <code>--worker</code> flag within a cluster where the master node does not contain any GPU.

**Comment by kmbae** [comment]
I also encountered the same error. I resolved the error by modifying the ```/var/snap/microk8s/current/args/containered-template.toml``` on the newly added node. I copied ```default_runtime_name``` and other missing **nvidia** related configs by referencing the  previously added node. After modification, reboot the newly added node, I found out that the initialization step passed!! (Tested under microk8s 1.23.3, Ubuntu 18.04.5 and 20.04.2)
