### ISSUE TITLE
Service with NodePort + externalTrafficPolicy: Local does not expose port on worker nodes

### ISSUE THREAD

**Issue by Firaenix** [canonical/microk8s#2971]
As title says.
Is this expected behaviour?
I need to expose a GRPC service to a cloud load balancer but I lose Client IP information if I use externalTrafficPolicy: Cluster.

I've tried behind NGINX before but that is creating a slew of different issues relating to proxy timeouts that I cant seem to fix.
Any help would be much appreciated

[inspection-report-20220309_102844.tar.gz](https://github.com/canonical/microk8s/files/8213417/inspection-report-20220309_102844.tar.gz)

**Comment by neoaggelos** [comment]
Hi @Firaenix, not sure if this issue is still relevant and/or valid. Stale bot notification got me here.

Unless I'm missing something from the issue description, https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip, using `externalTrafficPolicy: Cluster` should by design obscure the client IP address. Is this what you are experiencing?

**Comment by Firaenix** [comment]
Sorry I missed this notification, yes it's still valid.

Basically, if I set externalTrafficPolicy to Local on a service, any pods assigned to that service that get allocated to a `Worker` node, that is, not the control plane, are unreachable because the worker is not exposing the ports on the machine. Basically all traffic to that port on that worker node gets blackholed.

**Comment by dfry** [comment]
I am also experiencing this issue.  Would like to reopen this issue.

**Comment by dfry** [comment]
I opened a new issue here: https://github.com/canonical/microk8s/issues/4345
