### ISSUE TITLE
Addon Ingress disabled but still in `microk8s status` list as enabled

### ISSUE THREAD

**Issue by casabre** [canonical/microk8s#2984]
# Setup
I am running microk8s on multiple Raspberry Pi's 4B with 4 GB of RAM and Ubuntu 20.04 as a cluster. 

# Action
Disabling ingress via ssh took very very long so that the remote shell timed out. Thus, I believe that the service is an undefined state because the disabled service is still showing up in `status` list

```shell
ubuntu@ubuntu:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.xxx.xxx.xxx:19001 192.xxx.xxx.xxx:19001 192.xxx.xxx.xxx:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    helm3                # Helm 3 - Kubernetes package manager
    ingress              # Ingress controller for external access
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
    traefik              # traefik Ingress controller for external access
  disabled:
    dashboard            # The Kubernetes dashboard
    helm                 # Helm 2 - the package manager for Kubernetes
    host-access          # Allow Pods connecting to Host services smoothly
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    openebs              # OpenEBS is the open-source storage solution for Kubernetes
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
```

Running `microk8s disable ingress` shows the following
```shell
ubuntu@ubuntu:~$ microk8s disable ingress
Disabling Ingress
namespace "ingress" deleted
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": ingressclasses.networking.k8s.io "public" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": serviceaccounts "nginx-ingress-microk8s-serviceaccount" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": clusterroles.rbac.authorization.k8s.io "nginx-ingress-microk8s-clusterrole" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": roles.rbac.authorization.k8s.io "nginx-ingress-microk8s-role" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": clusterrolebindings.rbac.authorization.k8s.io "nginx-ingress-microk8s" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": rolebindings.rbac.authorization.k8s.io "nginx-ingress-microk8s" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": configmaps "nginx-load-balancer-microk8s-conf" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": configmaps "nginx-ingress-tcp-microk8s-conf" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": configmaps "nginx-ingress-udp-microk8s-conf" not found
Error from server (NotFound): error when deleting "/home/ubuntu/snap/microk8s/2952/tmp/temp.ingress.yaml": daemonsets.apps "nginx-ingress-microk8s-controller" not found
```

Trying to enable it again shows
```shell

ubuntu@ubuntu:~$ microk8s enable ingress
Addon ingress is already enabled.
```

Frankly spoken, I have currently now clue where to look in order to fix the setup? Any hint is appreciated. Thanks a lot!

[inspection-report-20220314_213549.tar.gz](https://github.com/canonical/microk8s/files/8248696/inspection-report-20220314_213549.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @casabre the `microk8s status` command will perform a `microk8s kubectl get all -A` [1] and based on the output it sees try to figure out if an addon is enabled or not. In the case of ingress if we see a pod starting with `nginx-ingress-microk8s-controller`  [3] we assume the ingress addon is enabled. In your cluster there is one such pod in "Terminating" state under the ingress namespace (`pod/nginx-ingress-microk8s-controller-nsbc2`). The obvious mitigation for your case is to make sure this pod has successfully terminated. Have a look at [4] on how this can be addressed.

There are a few issues worth mentioning here. The `microk8s status` command is does not perform a deep inspection of the state of each addon. For example, it does not check that all pods in an addon are up reporting a healthy state. An extensive inspection for all addons would take too long to complete and `microk8s status` would be too slow. However we could make it smarter so that cases such as the one we have here would be addressed. We could for instance in line [2] filter out the pods that are in `Terminating` state.


[1] https://github.com/canonical/microk8s/blob/master/scripts/wrappers/common/utils.py#L446
[2] https://github.com/canonical/microk8s/blob/master/scripts/wrappers/common/utils.py#L456
[3] https://github.com/canonical/microk8s-core-addons/blob/main/addons.yaml#L34
[4] https://containersolutions.github.io/runbooks/posts/kubernetes/pod-stuck-in-terminating-state/

**Comment by casabre** [comment]
@ktsakalozos thanks for the detailed information. Actually this issues was a more complicated one. 

Unfortunately, the microSD of one of my Raspberry Pi's in the cluster died (there is just a limited number of write operations and after that, the SD turns into read-only mode) and the Pi was not reachable anymore because the OS was not capable of acting anymore. It seems that the terminating Ingress controller was running on that node.

After receiving a new SD card, I cloned it and the brought the Pi back in the cluster and voilà... Ingress is now showing up as disabled.
