### ISSUE TITLE
How to implement "cloud disk" like aws's ebs?

### ISSUE THREAD

**Issue by fzyzcjy** [canonical/microk8s#3070]
Hi thanks for the microk8s! I need some cloud disk like aws's ebs. For example, I need to have a MySQL in my cluster (so NFS is too slow), and want it to be able to failover to another server when one server dies (so local-path disks are not possible). Is it possible in microk8s?

**Comment by ktsakalozos** [comment]
Hi @fzyzcjy, you probably need some form of distributed storage with replication. Have you looked at openebs [1]? We have an addon to make openebs installation easier [2]. With the v1.24 release scheduled in a few weeks time we will be shipping an addon for mayastor [3, 4] again from openebs.

[1] https://openebs.io/
[2] https://microk8s.io/docs/addon-openebs
[3] https://github.com/openebs/mayastor
[4] https://microk8s.io/docs/addon-mayastor

**Comment by fzyzcjy** [comment]
Thank you very much!

**Comment by fzyzcjy** [comment]
Hi @ktsakalozos , I wonder whether the performance is enough to run workload like MySQL when using OpenEBS?

**Comment by ktsakalozos** [comment]
That is a good question. In general running a database over a distributed filesystem is not recommended.

**Comment by fzyzcjy** [comment]
@ktsakalozos Well... Then does it mean that, we cannot use microk8s in production? Thanks

**Comment by ktsakalozos** [comment]
The recommendation of not using relational databases on distributed filesystems is not related to MicroK8s or any K8s distribution. The rational is that because of the distributed nature of filesystems there is a certain degree of uncertainty when data are really persisted on disk.

Have you looked at the mysql operator https://github.com/mysql/mysql-operator ? My guess is that some of these problems are addressed/well thought there?

**Comment by fzyzcjy** [comment]
@ktsakalozos Hi thanks for the reply, but:

> The MySQL Operator for Kubernetes currently is in a preview state. DO NOT USE IN PRODUCTION.
