### ISSUE TITLE
"storage" addon - is it *stable* for production environment?

### ISSUE THREAD

**Issue by fzyzcjy** [canonical/microk8s#3093]
Hi thanks for the library! I may need to use the "storage" addon. I know it will create PV that is *local* to the machine. But since one of my kubernetes environments have only two nodes, this is not a very big problem.

Given doc says "It is not intended to be used in a production environment", the question is, is it stable for production? Or is it unstable and buggy?

**Comment by neoaggelos** [comment]
Hi @fzyzcjy

The storage addon is labelled as not intended for use in a production environment due to limitations with the way hostpath storage is working in Kubernetes in general. Particularly, hostpath storage does not conform with a few things that people have come to expect out of Persistent Storage Volumes in Kubernetes:

- HostPath volumes do not enforce size request/limits (by design).
- HostPath volumes are tied to a single node in the cluster. What this means is that it is impossible (or, rather, manual, error-prone and time-consuming) to move pods using hostpath storage to a different node in the cluster.
- HostPath volumes will by default by owned by root, though MicroK8s makes sure that running workloads as non-root users do not have any issues.
- The hostpath provisioner currently does not support block device volumes.
- Tooling for backing up and restoring volume data is rather limited.

Given the limitations above, it is still worth noting some advantages:

- The [hostpath provisioner](https://github.com/canonical/hostpath-provisioner) is a simple, lightweight and fast operator running in the cluster.
- It is ideal for development clusters, where a developer can quickly spin up and tear-down PVCs without consuming volume quotas.

We have not seen users having any troubles with the provisioner itself. Rather, the drawbacks are due to limitations in the way Kubernetes handles hostpath storage. Basically, it comes down to picking what suits your need best. If you want production-grade storage for mission critical applications, then it is most likely better to go with a [CSI provisioner](https://kubernetes-csi.github.io/docs/drivers.html).

Finally, with the 1.24 release, we are adding a new addon for replicated storage based on OpenEBS mayastor, currently in alpha. See [the documentation page](https://microk8s.io/docs/addon-mayastor) for more details.

**Comment by fzyzcjy** [comment]
> Finally, with the 1.24 release, we are adding a new addon for replicated storage based on OpenEBS mayastor, currently in alpha. See [the documentation page](https://microk8s.io/docs/addon-mayastor) for more details.

I see. But I need it now and surely cannot wait for alpha :( Hopefully I will recheck this later when it stablizes.
