### ISSUE TITLE
Microk8s being tested with Sonobuoy fails

### ISSUE THREAD

**Issue by gustavosr98** [canonical/microk8s#3096]
I was testing Microk8s with [sonobuoy](https://github.com/vmware-tanzu/sonobuoy) and I always get one failing test. 

- ubuntu focal
- sonobuoy version -> v0.56.4_linux_amd64
- microk8s version -> snap v1.24 and v1.25 stable

Sonobuoy test results
```
sonobuoy results $RES
Plugin: e2e
Status: failed
Total: 7042
Passed: 343
Failed: 1
Skipped: 6698

Failed tests:
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]

Plugin: systemd-logs
Status: passed
Total: 1
Passed: 1
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.23.5-2+c812603a312d2b
Node health: 1/1 (100%)
Pods health: 6/6 (100%)
Errors detected in files:
Errors:
13 podlogs/kube-system/calico-node-zwgc5/logs/calico-node.txt
 5 podlogs/kube-system/calico-kube-controllers-5f67bfbd7b-98nbs/logs/calico-kube-controllers.txt
Warnings:
2 podlogs/kube-system/calico-kube-controllers-5f67bfbd7b-98nbs/logs/calico-kube-controllers.txt
2 podlogs/sonobuoy/sonobuoy/logs/kube-sonobuoy.txt
```

[sonobuoy](https://paste.ubuntu.com/p/WrxfhsX4PB/)
[kube-system/calico-node-zwgc5](https://paste.ubuntu.com/p/PgDSzCJyS7/)
[calico-kube-controllers-5f67bfbd7b-98nbs](https://paste.ubuntu.com/p/pcGnxgZSnh/)

**Comment by ktsakalozos** [comment]
Hi @gustavosr98, the conformance tests are expected to be run in multi node clusters. I read in [1] that the failing test is one of those tests that is expected to fail if you run it in single node clusters. You will have to provide a second node and join the two.

On every release we submit the conformance tests to cncf so we maintain the k8s conformance status. The results are found in [2]. For example in [3] you will find the test results for v1.23 along with a readme on how these tests were run.

Lastly, in the description of the issue you report the microk8s snap version being 1.24 or 1.25. This is not possible since 1.24 and 1.25 have not been released yet.


[1] https://github.com/canonical/microk8s/issues/3096
[2] https://github.com/cncf/k8s-conformance
[3] https://github.com/cncf/k8s-conformance/tree/master/v1.23/microk8s

**Comment by gustavosr98** [comment]
I just read the snap channel but not the actual version of microk8s. My bad

Thanks a lot for the clarification and the reference tests!
