### ISSUE TITLE
Default ingressclass has a name that is not standard (ngix ingress)

### ISSUE THREAD

**Issue by Orzelius** [canonical/microk8s#3158]
#### Summary

`kubectl --context microk8s get ingressclass --all-namespaces`

```
NAME     CONTROLLER             PARAMETERS   AGE
public   k8s.io/ingress-nginx   <none>       31d
```

The default `ingressClass` resource that comes with the ingress has a name of public.

#### What Should Happen Instead?

If the cluster has only on ingress controller nginx recommends to have a classname of `nginx`. Other tooling built for local kubernetes solutions will probably also expect the default name to be used. In my case I had to add a hack into the tool I'm working on to deploy an ingressclass resource with the name of nginx so the networking would work  https://github.com/garden-io/garden/pull/2907/commits/e5a535604996926c4848ff0ceeba8f9d5ee74406

#### Can you suggest a fix?

use the default name or create a second ingressclass with that name for backwards compatibility?

#### Are you interested in contributing with a fix?
 Sorry, have no experience with python ):

Greetings from kubecon!

```
microk8s ctr version

Client:
  Version:  v1.4.13
  Revision: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
  Go version: go1.16.15

Server:
  Version:  v1.4.13
  Revision: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
  UUID: 8f03b5c6-ae03-44df-b9df-3db0e3ee57b5
```

**Comment by ktsakalozos** [comment]
Thank you for reporting this @Orzelius. Having a second ingress "nginx" class makes sense since it would align us to what the upstream project is doing while staying backwards compatible. Would you be interested in contributing a section to the ingress manifest we apply [1]?

[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons/ingress/ingress.yaml
