### ISSUE TITLE
Inconsistent line length in lint rules

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microk8s#3177]
```
microk8s (master=)$ git grep line-length
.flake8:max-line-length = 100
installer/setup.cfg:max-line-length = 120
pyproject.toml:line-length = 100
tox.ini:    flake8 --max-line-length=120 --ignore=C901,N801,N802,N803,N806,N816
```

Also, I couldn't find any explicit value for `black` so I assume it's using the default value as 88.

#### Reproduction Steps

1. ...
2. ...

**Comment by ktsakalozos** [comment]
Hi @nobuto-m thank you for reporting this.

The `.flake` file is a left over from past lint checking and we will remove it.

The inconsistency in line lengths between `pyproject.toml` and `tox.ini` almost drove me mad a few months ago. `black` gets its line length target of 100 chars from `pyproject.toml`. `black` will try to get all lines below 100 chars but in some cases it may go over that limit (I guess because the code looks better?)! `flake8` on the other hand gets its limit of 120 chars in `tox.ini` and that is a hard limit. `flake8` will fail if a line is over this limit. So, overall 100 is a soft limit imposed by `black` and 120 is a hard limit imposed by flake8.
