### ISSUE TITLE
In HA clusters on nodes with separate private network interface, pods traffic uses public interface

### ISSUE THREAD

**Issue by madalinignisca** [canonical/microk8s#3402]
#### Summary
With HA-Cluster, on servers with separate network interface for private network, between pods traffic is routed on main public interface.

#### What Should Happen Instead?
Expected is to see traffic going through the private network interface.

#### Reproduction Steps
I observed the issue on Hetzner, and probably is happening on all providers that offer 2 distinct network interfaces per server.

1. Create 3 servers with private network added.
2. Install Microk8s on all nodes
3. Join server 2 and 3 on node 1 using the private ip
4. create a pod like nginx `microk8s kubectl run nginx --image nginx:latest`
5. get the pod ip using `microk8s kubectl describe pod/nginx`
6. create a pod to test pods network `microk8s kubectl run busybox --image busybox:latest -t -i`
7. run `traceroute IP` using the ip you collected for nginx pod.
8. first HOP should be the private IP of the hosting node, but the result is the public ip.

#### Introspection Report
[inspection-report-20220823_062701.tar.gz](https://github.com/canonical/microk8s/files/9399889/inspection-report-20220823_062701.tar.gz)

#### Can you suggest a fix?
I'd like to make a note, that on non ha cluster (disabling ha cluster addon), creating a non ha cluster with any amount of nodes, pod to pod uses the private ip of each nodes as expected (I think so).

#### Are you interested in contributing with a fix?
no (no idea where to start from)

**Comment by madalinignisca** [comment]
Learned later, that with Flannel, the network is an overlay and I don't know how to check how traffic is transported. If it uses the private ip, that would be great news.

**Comment by neoaggelos** [comment]
Hi @madalinignisca 

By default, MicroK8s uses the Calico CNI, which defines an overlay network using vxlan for all cluster traffic. The "underlay" network can be configured by setting the `IP_AUTODETECTION_METHOD` configuration in https://github.com/ubuntu/microk8s/blob/master/upgrade-scripts/000-switch-to-calico/resources/calico.yaml#L4439-L4440

By default, this is `first-found`, which means pick any interface found on the host. When creating an HA cluster, this will change to `can-reach=$ip`, which means pick the interface that can reach the internal IP of the other node.

In general, you can configure this value manually by editing `/var/snap/microk8s/current/args/cni-network/cni.yaml`, and picking the IP autodetection method as needed. See the [IP autodetection methods](https://projectcalico.docs.tigera.io/reference/node/configuration#ip-autodetection-methods) in the Calico documentation for more details.

After editing the file, make sure to reapply it with `microk8s kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml`. Note that it might be required that you delete and recreate any existing pods (so that calico uses the correct underlay network).

The above should work, please reach out if anything fails. Thanks!
