### ISSUE TITLE
Microk8s HA not working

### ISSUE THREAD

**Issue by odsevs** [canonical/microk8s#3492]
#### Summary
Losing a node in a microk8s cluster causes the other nodes to become NotReady, sometimes for 15 minutes.
This issue is not systematic.
Concretely, this causes an interruption of service for our applications running on this cluster.

#### What Should Happen Instead?
The other nodes should remain ready and we have no interruption of service.

#### Reproduction Steps
(In parentheses: some precisions regarding the logs in the attached files)
1. Create a microk8s cluster on three nodes (three VM with CentOS 7.9)
2. Wait till all nodes are ready
3. Power off one of the nodes (node 2)
4. Immediately after that, all nodes appear Not Ready
5. Some of the remaining nodes can become ready again after a few seconds (node 3)
6. Other nodes in some cases need 15 minutes to become ready again (node 1)

#### Can you suggest a fix?
In the kubelite logs, we can see errors with "the object has been modified; please apply your changes to the latest version and try again" when the issue is occurring. This makes us think that the root cause lies within the Dqlite database.

#### Introspection Report
[inspection-report-20221006_105621.tar.gz](https://github.com/canonical/microk8s/files/9725107/inspection-report-20221006_105621.tar.gz)
[inspection-report-20221006_113207.tar.gz](https://github.com/canonical/microk8s/files/9725111/inspection-report-20221006_113207.tar.gz)
[node-2-poweroff-events.txt](https://github.com/canonical/microk8s/files/9725112/node-2-poweroff-events.txt)

**Comment by odsevs** [comment]
Issue also posted here: https://app.slack.com/client/T09NY5SBT/threads

**Comment by flokoenig** [comment]
We might have the same issues. I wrote a post about it two days ago on [stackexchange](https://askubuntu.com/questions/1436043/microk8s-ha-cluster-node-failover-depends-on-which-node-fails). In short: I _believe_ it _could_ be related to the failed node running some or all of the addon-controllers.

**Comment by balboah** [comment]
Experienced the same issue while testing what happens if I stop a node.
I have 3 master nodes, 3 nodes on stand by.

Stopped one standby, all good and it disappeared from standby list (now 3 masters & 2 standby).
Stopped one master, this time also all good. A new master was selected (still 3 masters & 2 standby).

Stopped another master (after 3 nodes were shown as ready again), all nodes except one now got marked NotReady.
Service stopped working because "no local pods running" on NotReady nodes.
microk8s status shows "no endpoints" on master and standby fields.
Started the master again, cluster recovers.

Waited 30 minutes in case replication or such needs to catch up (how do you check this?), but same NotReady issue happened again when stopping this node once more.
microk8s status now shows 3 nodes as masters and 2 standby (as opposed to "no endpoints" on previous attempt),
but nodes are still NotReady and logs show api server request timeouts.

Started the node again, cluster has not recovered after maybe 15 minutes. I'll keep it running to see if it does eventually.

To fill in on the theory from @flokoenig, this last stopped node was also the initial node that created the cluster.
I've also seen the "the object has been modified; please apply your changes" all the time, also when the cluster appears to be working fine. Maybe unrelated?

**Comment by balboah** [comment]
No recovery after an hour

**Comment by GDegrove** [comment]
@neoaggelos
