### ISSUE TITLE
microk8s dbctl backup Error

### ISSUE THREAD

**Issue by logici** [canonical/microk8s#3531]
#### Summary

My env:
- Microk8s 1.24
- OS: Ubuntu 20.04.1 LTS
- Kernel: 5.4.0-60-generic

I execute `microk8s dbctl backup` command. It print thie.
```
Backing up the datastore
INFO[0000] mode: backup-dqlite, endpoint: unix:///var/snap/microk8s/current/var/kubernetes/backend/kine.sock:12379, dir: /tmp/tmpg8rxtmqb/backup-2022-10-31-09-48-42 
FATA[0012] couldn't create keyfile /tmp/tmpg8rxtmqb/backup-2022-10-31-09-48-42/508.key: open /tmp/tmpg8rxtmqb/backup-2022-10-31-09-48-42/508.key: too many open files 
Backup process failed. 1
```
#### Reproduction Steps

1. ...
2. ...

**Comment by neoaggelos** [comment]
Hi @logici, thank you for raising this issue.

The error message clearly indicates the problem, and that is the shortage of open files on your system. A workaround would be to increase this limit.

However, after taking a look at the code, it seems that we leave a few too many open files lying around, and https://github.com/canonical/go-migrator/pull/2/files should help with this.

After merging, the fix is typically released to `1.24/edge` within a day, and then promoted to stable with the next minor release of Kubernetes.

**Comment by logici** [comment]
Thanks for your reply. 
And it means that I can't use `microk8s1.24/stable` with fixed backup tool. The fixed backup tool must be used in `microk8s1.25/stable` or `microk8s1.24/edge`. Is that so?

**Comment by neoaggelos** [comment]
Hi, sorry for missing this.

Both 1.24/edge and 1.25/edge should get the fix (and, eventually, with the next Kubernetes patch release, it will move to 1.24/stable and 1.25/stable)

**Comment by logici** [comment]
Thanks for your help.
And I will close this Issue.
