### ISSUE TITLE
host-access not working

### ISSUE THREAD

**Issue by olamy** [canonical/microk8s#3547]
#### Summary

I have enabled `host-access` 
```
ubuntu@brahman:~$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 10.0.0.15:19001
  datastore standby nodes: none
addons:
  enabled:
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated
```

From a pod running on a node with an app listening to port 8081, I get this error
```
curl http://10.0.1.1:8081
curl: (7) Failed to connect to 10.0.1.1 port 8081 after 1 ms: No route to host
```

#### Reproduction Steps
Is there any logs somewhere I can look?

**Comment by olamy** [comment]
[inspection-report.tar.gz](https://github.com/canonical/microk8s/files/9958263/inspection-report.tar.gz)

**Comment by olamy** [comment]
there is one master node and 3 worker nodes.

**Comment by olamy** [comment]
master have a file 
```
sudo cat /var/snap/microk8s/4094/var/lock/host-access-enabled
10.0.1.1
```
but workers not
```
sudo cat /var/snap/microk8s/4094/var/lock/host-access-enabled
cat: /var/snap/microk8s/4094/var/lock/host-access-enabled: No such file or directory
```

does this mean it can only work for master nodes? (e.g all nodes must be master)

**Comment by neoaggelos** [comment]
Hi @olamy 

Thank you for reporting this. The `host-access` addon is mostly meant for single-node MicroK8s clusters, as a means of reaching out to local services via a stable IP (e.g. 10.0.1.1).

For MicroK8s clusters, it does not really make sense for a few reasons:
- 10.0.1.1 would mean the host that the pod is running on each time, leading to confusion if for example some service is not running on a host.

I would suggest the following: Instead of 10.0.1.1, you could directly use the host IPs (or hostnames), e.g. 192.168.1.31. This has the extra benefit that your pods talk to the correct host regardless of the node that they are scheduled on.

If, for whatever reason, you know that `host-access` addon is the way to go, you should be able to configure each worker node manually by doing this:

```
echo 10.0.1.1 | sudo tee /var/snap/microk8s/current/var/lock/host-access-enabled
sudo snap restart microk8s
```

I am interested in your use-case, perhaps there is a cleaner solution to your problem, but it is unclear to me what you want to achieve. Happy to advise further if you share some more information.

**Comment by olamy** [comment]
Thanks for the answer!
my use case is to use docker within a pod. To build images and to use this https://www.testcontainers.org/ (see  https://www.testcontainers.org/features/configuration and the env var TESTCONTAINERS_HOST_OVERRIDE which is set to 10.0.1.1)

**Comment by olamy** [comment]
Thanks for the answer.
