### ISSUE TITLE
Mayastor Addon with latest version - 2.0

### ISSUE THREAD

**Issue by datacore-tilangovan** [canonical/microk8s#3732]
#### Summary
Mayastor Addon with latest version - 2.0

#### Why is this important?
Mayastor Addon with latest version - There are new features and bug fixes with the latest version of Mayastor 2.0

#### Are you interested in contributing to this feature?
Yes, we would like to contribute to place the new version of mayastor addon. we need further details on this to proceed.

**Comment by neoaggelos** [comment]
Hi @datacore-tilangovan, thanks for creating this PR. I just went through the release notes for 2.0.0 in https://github.com/openebs/mayastor/releases/tag/v2.0.0

I see some changes that I like in Mayastor 2.0.0, namely the single helm chart to deploy all of the mayastor components in the cluster.

For MicroK8s, we initially used a fork of the available helm charts due to required configurations that were missing from upstream, and for which the PRs were dropped https://github.com/openebs/mayastor-control-plane/pull/250 and https://github.com/openebs/mayastor/pull/1122

Further, we also provide and validate mayastor arm64 builds, which requires building and maintaining our own images for mayastor. The whole process is described in https://github.com/canonical/microk8s-core-addons/blob/main/addons/mayastor/chart/README.md#L169

This needs to be updated considerably for 2.0.0.

**Comment by datacore-tilangovan** [comment]
Hi @neoaggelos Thanks for your response !! 

Any updates on how we are going to proceed further on this ? Does upgrading mayastor in Microk8s addon will be owned by canonical itself. If yes, any timelines ? 

If this needs contribution from our side, Please do let us know how can we help to get this done as soon as possible. Thanks !

**Comment by neoaggelos** [comment]
Hi @datacore-tilangovan 

It definitely requires work from our side since we are building images for amd64 and arm64. I also see that the helm charts have changed significantly from 1.0.0, so we will have to take a look at them as well.

We will pick this up shortly and will keep in the loop if we encounter any blocking issues. Thanks!

**Comment by ktsakalozos** [comment]
Hi @datacore-tilangovan , the upcoming 1.27 release will include Mayastor 2.0.0. Please have alook at https://github.com/canonical/microk8s/issues/3732 to see what we had to do to port it to MicroK8s. Thanks.
