### ISSUE TITLE
Allow addons to use external Python dependencies

### ISSUE THREAD

**Issue by krakowski** [canonical/microk8s#3784]
#### Summary
The [addon system](https://microk8s.io/docs/addons) already allows running python scripts as seen in the [addon template repository](https://github.com/canonical/microk8s-addons-repo-template/blob/main/addons/python-hello-k8s/enable). Unfortunately, this way the python interpreter (`3.6.9`) shipped within the `microk8s` snap is used, which makes it very difficult to use external libraries within plugin scripts.

At the moment I place common utility scripts inside a folder called `common` within the addon's root directory (same level as `addons.yaml`) and add append this path to Python's search path at the beginning of the `enable`/`disable` scripts.

 ```
 #!/bin/env python3

import os
import sys

# Add common utilities to Python path
sys.path.append(f'{ os.path.dirname(os.path.realpath(__file__)) }/../../common')

...
```

This could be enhanced by allowing addon repositories to specify some kind of initialization mechanism which installs all required python dependencies inside the snap context. I could think of the following solutions:

  1. An executable `init` file inside the repositories root folder. This would be more generic as it could execute any command.

  2. A dependency block within the `addons.yaml` file.
      ```yaml
      dependencies:
        python:
          - sh>=2.0.0
          - rich==13.3.1
          - kubernetes
      ```

Both solutions would require the user to invoke some `microk8s` command  in order to install the dependencies.

#### Why is this important?

  - Addon scripts could (re-)use existing (Python) libraries/frameworks (e.g. [`sh`](https://github.com/amoffat/sh), [`rich`](https://github.com/Textualize/rich), [`kubernetes`](https://github.com/kubernetes-client/python), ...)

  - Smaller and more readable addon scripts, since a lot of boilerplate code can be hidden using external libraries.

#### Are you interested in contributing to this feature?
Once a good solution is found, I would be glad to implement it.

**Comment by ktsakalozos** [comment]
Thank you @krakowski for reaching out and for the suggestions.

In order to support user repositories with addons in any language we would like to abstract as much as possible the relation between the addons and the microk8s snap. Ideally we would like addons to have hooks (such as the enable/disable) that microk8s would call throughout the addons lifecycle. For example, we now have the enable and disable hooks but we could consider an update one or an init one.

The fact that the python interpreter is in the microk8s snap should be considered a legacy artifact. We do not have any plans to remove the interpreter but as we move forward we cannot ensure that there will not be some python update that would break some addons repositories.

So the approach of an extra init hook would be more aligned to where we want to go.

Maybe we could get some ideas from the lifecycle management of charms [1] and extend it to include upgrades and snap refreshes. Your thoughts?  

[1] https://juju.is/docs/sdk/a-charms-life
