### ISSUE TITLE
microk8s status --wait-ready improvements 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/microk8s#3927]
hello

`microk8s status --wait-ready` can be slightly improved.

1. when timeout is added (eg `microk8s status --wait-ready --timeout 150`) it should return non-zero on exit if timed out
2. it should wait for all addons to be up. For example, if metallb is selected, microk8s says that it is ON. However, I see that pods are not available. (to reproduce just block quay.io in your proxy). So, wait ready really need to wait for all addon pods to start

**Comment by neoaggelos** [comment]
Thanks for reporting this @beliaev-maksim. I want to provide some more context on this and write down some thoughts that I have been experimenting with. I would like to link this issue with #2572 

I think this is related to the "simple" nature of addons as they have been historically implemented in MicroK8s. Currently, MicroK8s does a very simplistic check to see if an addon is enabled: look for a specific resource in the cluster (e.g. a daemonset has been created) or a file in the local node.

This allows `microk8s status` to quickly determine which addons are "enabled" and which are "disabled". Obviously, this calls for false positives (e.g. if you manually deploy a resource that conflicts with what the respective addon deploys, the addon is shown as enabled).

An important note before moving on: The purpose of `microk8s status` is to very strictly check whether the MicroK8s cluster is up and running, along with the status of the underlying datastore. `microk8s status` is not at all involved with whether any particular addon has been enabled properly or is functioning as expected. Further, doing this in a careless manner would lead to bigger issues, since the `microk8s enable/disable` commands are using `microk8s status` internally to check that the Kubernetes services are up before proceeding.

---

I believe that what is described here reads to me more like a `readiness` check. An addon may be enabled (e.g. the respective daemonset exists) but not yet ready (e.g. the pods have not come up).

Now, a readiness check might vary greatly between addons. For others it might be just a `kubectl wait --for=condition=ready $pod`, whereas for others like `rbac` it might be something more involved (e.g. do an apiserver request impersonating a read-only user and expect it to fail.

One more important note, a `readiness` check is not equivalent to or meant to replace the addon tests. The `readiness` check should simply probe the respective addon resources and check whether they are ready to serve requests.

To that end, I would recommend two additions:

- Allow individual addons to have a `ready` hook, which executes a readiness check probe (with a timeout). If the addon is ready, the probe is expected to exit with status code 0. For simplicity and backwards compatibility, if an addon does not have a readiness check hook, then it is implicitly assumed to be ready.

- Extend `microk8s status` with a new flag `--wait-for-ready-addons=true --timeout=900`, set to false by default. If this flag is set, then microk8s status will work as is, but also block (optionally until the specified timeout) until all readiness checks are successful.

This ensures that backwards-compatibility is preserved, and further that we properly support the use case described in the issue without surprises.

Thoughts @beliaev-maksim @ktsakalozos ?

**Comment by beliaev-maksim** [comment]
@neoaggelos I support this API like idea with specifying hooks for checks. Then it is up to the addon to provide relevant info

and +1 for additional flag for addons health check. That ensures backwards compatibility. And if we see great use of it, then with the next major version these two could be merged

**Comment by ktsakalozos** [comment]
@beliaev-maksim on your first point of returning 
a non-zero code in case the cluster in not ready it should be a fairly easy patch to: https://github.com/canonical/microk8s/blob/f4eaff59f1584f11fceb184d93dedca80de712d5/scripts/wrappers/status.py#L173 

Would you be interested in contributing this?

**Comment by stas-sbi** [comment]
I'm here to support the need or waiting for addons to be ready. There is no easy way to know that the cluster is ready after an addon is enabled. For example configuring upstream DNS address requires restarting dns addon which results in many services (such as controller-manager) restarted as well and I have to wait an undefined period of time before doing operations which depend on the controller manager.

For DNS specifically I use the following workaround right now:
```shell
microk8s disable dns && microk8s enable dns:"$DNS_FORWARDERS" &&
    kubectl -n kube-system wait deployments.apps coredns --for=condition=Available --timeout=5m

```

**Comment by giner** [comment]
I'm here to support an option to wait for addons to be ready. There is no easy way to know that the cluster is ready after an addon is enabled. For example configuring upstream DNS address requires to restart dns addon which results in many services (such as controller-manager) restarted as well and I have to wait an undefined period of time before doing operations which depend on the controller manager.

For DNS specifically I use the following workaround right now:

```shell
microk8s disable dns && microk8s enable dns:"$DNS_FORWARDERS" &&
    kubectl -n kube-system wait deployments.apps coredns --for=condition=Available --timeout=5m
```
