### ISSUE TITLE
Internet connectivity check fails if ICMP traffic is restricted

### ISSUE THREAD

**Issue by asmithdt** [canonical/microk8s#3978]
#### Summary

When trying to install on macOS I get a failure to connect to the internet, the check is done via a ping (ICMP) traffic which isn't allowed on my corp network. However http/https (which are the connections actually required) are fine. I can't see any other use of ping other than a test.

#### What Should Happen Instead?

The internet check should check for http(s) connectivity instead of using ping.

#### Reproduction Steps

1. be on network that disallows ICMP traffic
2. microk8s install

#### Introspection Report

N/A

#### Can you suggest a fix?

https://github.com/canonical/microk8s/blob/master/installer/vm_providers/_base_provider.py#L131

`curl --fail --head https://snapcraft.io` instead perhaps?

#### Are you interested in contributing with a fix?

Yes

**Comment by neoaggelos** [comment]
Hi @asmithdt 

Thank you for raising this, this has also been discussed in the past, but I do agree that your proposal sounds quite sound.

We could even attempt both (try the ping, then fallback to curl if that does not work), and if any of the two works then proceed with the installation assuming that we have network connectivity.

Contirbutions are welcome! Otherwise we will work on this soon. Thanks for raising this!
