### ISSUE TITLE
Failure Domain behavior is inconsistent

### ISSUE THREAD

**Issue by samdulam** [canonical/microk8s#4024]
#### Summary
We have a 6 node multi-dc stretched Microk8s Cluster. Each DC has 3 nodes, and all are masters. Nodes in DC1 are in failure-domain=1 and DC2 has failure-domain=2.
Nodes are added into the cluster in the following order:
DC1-Node1
DC1-Node2
DC1-Node3
DC2-Node1
DC2-Node2
DC2-Node3

The result is that all nodes in DC2 are in standby mode for HA. 

Where are failure domains coming into picture with this scenario?

I can get one of the standby nodes in DC2 to become a voter by restarting a node in DC1, but I want to understand if failure domain should take care of that for me.

#### What Should Happen Instead?
I would have expected to have at least one voter in the second failure domain.

**Comment by ktsakalozos** [comment]
Hi @samdulam, the behavior you are seeing is because joining a node does not cause a reelection of the voters. In some cases this makes sense but your expectations (re-balance of voters) is also reasonable. We will need to work on this feature. In the mean time the workaround you describe is what is available. You can alternate between DCs when joining of nodes or to force a restart of a voter on DC1 so that it moves to DC2.

**Comment by freeekanayaka** [comment]
Note that in this very specific case it does not help to have a voter in DC2: if you lose DC1 your cluster will become unavailable (since you are left with only 1 voter out of 3).

In order for failure domains to be effective, there should be 3 failure domains.
