### ISSUE TITLE
Pods cannot connect to internet when behind a proxy, have to manually export http_proxy

### ISSUE THREAD

**Issue by matthewygf** [canonical/microk8s#4057]
#### Summary

Pods cannot connect to the internet by default when behind a proxy. Have to set 'export http_proxy=http://xxxx:xxx' manually within pods for them to work.

#### What Should Happen Instead?

Pods should be able to connect to the internet via proxy, when the environment variable HTTP_PROXY is set for '/etc/environment/' or 'var/snap/microk8s/current/args/containerd-env' that should have also set the pods environment.

#### Reproduction Steps

1. Have a proxy setup
2. Use default microk8s containerd
3. Launch a curl pod, curl google.com
4. if now set 'export http_proxy=http://xxxx.xxx', things should work.

**Comment by neoaggelos** [comment]
Hi @matthewygf 

This is in fact working as intended. The containerd environment variables are not expected and must not be part of the environment of any running workloads.

If you need an http_proxy to access the network, you must also configure it per pod, since there is no way for them to get this from the host.

One could possible attempt to automate this by using [mutating webhooks](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook), but that is not a setup that is supported out of the box.

**Comment by matthewygf** [comment]
Hmmm, got it, thanks for the reply.
