### ISSUE TITLE
On upgrade of MicroK8s cluster, addons list is no longer correct

### ISSUE THREAD

**Issue by jtraxy** [canonical/microk8s#4088]
#### Summary
After upgrading the MicroK8s version of a cluster, you have to manually update the addons list, or it is no longer correct.

This is what you seem to have to run:
```
microk8s addons repo add core /snap/microk8s/current/addons/core --force
microk8s addons repo add community /snap/microk8s/current/addons/community --force
```
Or if you don't want to use `--force`, you can remove core and community repos and add them back (`--force` is just one less step).

#### What Should Happen Instead?
I would expect the upgrade to automatically perform this for me.

#### Reproduction Steps
Yes.

1. Set up a cluster
2. Run `microk8s enable community`
3. Run `microk8s status` and observe the addons list
4. Upgrade the cluster to the next version
5. Run `microk8s status` and observe the addons list is incomplete

#### Introspection Report
-

#### Can you suggest a fix?
No.

#### Are you interested in contributing with a fix?
No.

**Comment by ktsakalozos** [comment]
Hi @jamest-portainer sorry for the late reply. This behavior is by design, let me explain.

The addons (most of the time) deploy workloads on your k8s cluster. When the cluster updates the deployed workloads do not change therefore the enable/disable scripts of the workloads should follow the workloads that are currently on the cluster. Furthermore, users are expected to go and edit the addon to customize them based on their needs so we do not want to overwrite any such changes.

If the user wants to get the latest version of the addons in a repository they would need to explicitly do a `microk8s addons repo update "repo-to-be-updated"`.

**Comment by jamest-portainer** [comment]
I think I understand. Thank you!
