### ISSUE TITLE
Question: How to use system containerd in place of the microk8s containerd service

### ISSUE THREAD

**Issue by alanpjohn** [canonical/microk8s#4171]
#### Summary
As part of a research project, I am trying to use different runtimes with microk8s which include gVisor, Kata and some more. 
The containerd on my local machine is configured will all the runtimes I need to run with and I have been successfully able to run my applications on all the different runtimes using the `crictl` tool. I have been trying to now use that containerd version as part of my microk8s setup.

I tried editing the kubelet args at `/var/snap/microk8s/current/args/kubelet` to use a different containerd and also tried editing `/var/snap/microk8s/current/args/containerd.toml` to configure the microk8s containerd but to no avail as the configuration files get overwritten whenever I restart microk8s.

#### What Should Happen Instead?
I am not sure if what I am doing is the right approach or if it already working as intended but
I was expecting microk8s would launch with kubelet using the containerd on host machine when `/var/snap/microk8s/current/args/containerd.toml` is edited

#### Reproduction Steps

```bash
$ microk8s version
MicroK8s v1.27.4 revision 5643
```
Make any changes made to `/var/snap/microk8s/current/args/containerd.toml`  or `/var/snap/microk8s/current/args/kubelet` and check if they persist

#### Introspection Report
[inspection-report-20230823_155757.tar.gz](https://github.com/canonical/microk8s/files/12420653/inspection-report-20230823_155757.tar.gz)

#### Can you suggest a fix?

NA

#### Are you interested in contributing with a fix?
Yes, if  there is any required.

Thanks

**Comment by berkayoz** [comment]
Hey @alanpjohn ,

For the `containerd.toml` you'd need to update the template file [here](https://github.com/canonical/microk8s/blob/master/microk8s-resources/default-args/containerd-template.toml) in order to persist your changes as this template gets updated with different dynamic configurations and creates the toml to be used. As for kubelet the changes should persist. We don't officially support such scenarios, as the snap has tightly bundled components. Make sure you go through upstream instructions on changing the container runtime as well.

Also beware this won't likely work on strict channels of microk8s.
