### ISSUE TITLE
Accessing HA cluster when one of the nodes is down

### ISSUE THREAD

**Issue by mike-pisman** [canonical/microk8s#4315]
Hi,

I have a baremetal microk8s cluster with 3 nodes.  I have some questions regarding the fail over.
I wanted to see how HA actualy going to handle a failure, so for the testing, I shutdown one of the nodes.

First, when the node went down, some of the pods stuck in the terminating state. I read in the documentation, that this is expected, unless the node is drained before going down. I did not find the solution for this problem though. How can I turn off this graceful shutdown, so the pods will be automatically deleted if the node is not reachable. I know this is more kubernetes related, but was hoping someone here could help, since I am using microk8s ha.

Second, how do I handle access to the cluster when I have multiple nodes? I have copied kubeconfig(generated with `microk8s config` command) to my local machine and can access the cluster when the node is up. However, if that node is down, I cannot use kubectl. How can I specify multiple servers in the config, so kubectl would automatically try to connect to another server, if one is down. Or is this only possible with etcd and loadbalancer setup?

Thanks

**Comment by ktsakalozos** [comment]
Hi @mike-pisman,

If one of the nodes goes down Kubernetes will spawn the running containers to another node. There are however exceptions, such as deamonsets, statefulsets, or in general pods bound to a node due to a resource that exists only on the initial node.

Having a single kubeconfig file pointing to multiple API servers is not supported [1]. You could place a loadbalancer infront of your API servers to address this limitation.

[1] https://github.com/kubernetes/kubectl/issues/1121

**Comment by mike-pisman** [comment]
@ktsakalozos, thank you for sharing. I will look into setting up a loadbalancer, I believe haproxy should be able to handle this.

To add to this, as I found out, the Kubernetes issues a block upon reboot, so it can evict the workloads; However, it's not guaranteed that the node will be able to do it before timeout or at all. So Kubernetes 1.28 introduces [Non Graceful shutdown feature](https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/), with which you can taint node to forcefully evict all pods, until the taint is removed.
