### ISSUE TITLE
Cannot enable gpu addon on aarch64 instances (aws g5g.metal)

### ISSUE THREAD

**Issue by copiltembel** [canonical/microk8s#4454]
#### Summary
Installing microk8s on a [g5g.metal](https://aws.amazon.com/ec2/instance-types/g5g/) instance (aarch64 with Nvidia T4G, the `gpu` addon is not available.

#### What Should Happen Instead?
I should be able to enable microk8s `gpu` addon.

#### Reproduction Steps
1. Provision a [g5g.metal](https://aws.amazon.com/ec2/instance-types/g5g/) instance on AWS.
2. Install microk8s: `sudo snap install microk8s --classic`
3. Wait for it to be ready: `microk8s status --wait-ready` (the `gpu` is not listed among addons)
4. Try to enable `gpu` addon anyway: 
```
$ sudo microk8s enable gpu
Addon gpu was not found in any repository
```

#### Introspection Report
[inspection-report-20240308_164158.tar.gz](https://github.com/canonical/microk8s/files/14540863/inspection-report-20240308_164158.tar.gz)

#### Are you interested in contributing with a fix?
yes, but I doubt I have the skills...

**Comment by copiltembel** [comment]
Is there a workaround that I could use, like manually enabling the `nvidia-container-runtime`?

**Comment by neoaggelos** [comment]
Hi @copiltembel 

Thank you for raising this. This is disabled at the addon level, simply because there is no CI testing for microk8s gpu on arm64 arch.

If you want to try it out, you could do:

```
sudo vim /var/snap/microk8s/common/addons/core/addons.yaml
```

Then look for the `nvidia` (and `gpu`) addons and change the `supported_architectures`:

```yaml
      supported_architectures:
        - amd64
        - arm64            # add this line
```

Then, `sudo microk8s enable gpu` should work. This will deploy the gpu-operator on the instance, so if T4G works with the gpu-operator, then it should be smooth.

To re-iterate, this is not enabled by default because the gpu addon is only tested on amd64 for new releases.

**Comment by copiltembel** [comment]
Thank you, that worked!

To test as described in the [microk8s gpu add-on installation guide](https://microk8s.io/docs/addon-gpu), I had to use this image from dockerhub instead: `nvidia/samples:vectoradd-cuda11.6.0-ubuntu20.04`

because the `k8s.gcr.io/cuda-vector-add:v0.1` one does not have an arm64 version
