### ISSUE TITLE
Update addons

### ISSUE THREAD

**Issue by marwenbk** [canonical/microk8s#4465]
How can i update addons, in my case i have Helm v3.9.1+unreleased (jul 2022), i updated microk8s to v1.29 but helm didn't update,

**Comment by bschimke95** [comment]
Hi @marwenbk 

Workloads running in the cluster, unless specified otherwise in the documentation, will NOT be upgraded as part of a MicroK8s upgrade. This includes both enabled add-ons and the CNI. Currently, the most effective way to upgrade add-ons is to use `microk8s disable <add-on>` and then re-enable them.
See https://microk8s.io/docs/upgrading.

In-place upgrades are not supported.
See https://github.com/canonical/microk8s/issues/3678

**Comment by gioargyr** [comment]
Hello,

I just disabled `ingress` addon and then re-enabled it.
Nothing changed.
I am also monitoring all files in `/var/snap/microk8s/common/addons/core/addons/ingress` and I do not see any change happening.
It's still on version `v1.8.0` as when it was first enabled on June 2024, when I still had Kubernetes 1.28
Now, I am in Kubernetes 1.30.10
I am trying to find a way to upgrade all the core addons and there's really minimal information and almost no documentation.

Any ideas or advice on what to follow?

**Comment by NerdyGriffin** [comment]
Sorry for resurrecting this old conversation, but I wanted to leave this here for anyone else who finds this in the future trying to figure out how to update their addons.

> Any ideas or advice on what to follow?

You may need to run `microk8s addons repo update core` before re-enabling the addon. That should update the `enable` script within `/var/snap/microk8s/common/addons/core/` to install the newer version
